### ISSUE TITLE
Sample vs population mean, sd, etc.

### ISSUE THREAD

**Issue by hannesbecher** [carpentries-incubator/statistical-thinking-public-health#23] opened 2022-02-21 11:49 UTC
In "Estimating the mean, variance and standard deviation" (or perhaps somewhere else) would it be good to introduce the difference between estimates from samples and parameters of distributions/populations?

**Comment by ezherman** [comment] 2022-02-21 16:46
Hi Hannes, thanks for your suggestion!

I believe this is sort of covered in [episode 2](https://carpentries-incubator.github.io/statistical-thinking-public-health/02-estimation/index.html), where it is shown that the sample mean varies around the population mean. Or is this not what you are referring to?

**Comment by hannesbecher** [comment] 2022-02-21 17:57
Hi Ezra,

First, I want to say that this is my opinion and just a suggestion. I'm no upset if this is not included and I am not claiming to an authority here.

You are right, it is "sort of" covered. I think though in episode 1 one could be clearer. The way things are explained ATM seems to throw together samples and populations.

The example is to estimate parameters of the distribution of female heights from a sample of 1000 observations. There, mean and variance are defined in terms of expectations. To me (I may be wrong) an expectation makes only sense if you already know/assume the distribution. Analogously, defining variance in terms of an expectation to me makes only sense for a random variable or a population, but not for a sample. For a sample I'd suggest writing out a sum of squares divided by (n-1) as [here](https://en.wikipedia.org/wiki/Variance#Unbiased_sample_variance) without E operators. Same for the mean.

In the section on "Estimating the mean, variance and standard deviation through simulation", I would then stress that it is now assumed that we know the correct parameters.

These things may seem subtle but I think it is good to be rigorous to avoid confusion.

**Comment by ezherman** [comment] 2022-02-28 16:20
Thanks for expanding on your thoughts Hannes! I haven't had a chance yet to dive into this issue, but I will look into it and get back to you.

**Comment by ezherman** [comment] 2022-04-28 13:49
Hi @hannesbecher, thanks again for opening this issue. I hope that I have resolved it by defining the mean and variance for the sample, without E() and including the (n-1) denominator. If you have time at some point, could you let me know whether you think the commits have resolved the issue?

On a relate note, this issue got me thinking about the definition of the linear model used in subsequent lessons. 

- I've defined the simple linear regression model as E(y) = beta_0 + beta_1 * x_1. 
- In the Gelman book, the authors define the model at the observation level, i.e. y_i = beta_0 + beta_1 * x_1i + error_i. 

I chose for the former because:
- It helps learners realise that the model predicts the mean.
- It circumvents a formal definition of the error, which reduces the cognitive load. Residuals do make an appearance in the assumptions episode, albeit only visually. 

This issue has me wondering, do you think I should define the model in terms of \bar{y} (y with a bar) instead of E(y)? Since the model estimates E(y), but the output is \bar{y}.

I will tag @3mmaRand here. Emma, I think you have defined the model in terms of E(y) in the past - do you have an opinion on whether \bar{y} or E(y) would be more appropriate for the regression model?

**Comment by hannesbecher** [comment] 2022-04-29 07:47
Hi @ezherman ,
I am very happy with this. I am not knowledgeable enough to say whether there is one right or best way...

**Comment by ezherman** [comment] 2022-04-29 08:53
Thanks for taking a look @hannesbecher, I'm glad to read that you feel the issue has been resolved.

No worries about the regression equation question, it will be fine either way for future workshops. I'll make a note to dive into the question at another time & close this issue now.

**Closed as completed by ezherman** 2022-04-29 08:53 UTC
